// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int numTests = Integer.parseInt(args[0]);
		int greater = 0;
		int lower = 0;
		for (int i = 0; i < numTests; i++) {
			double random = Math.random();
			if (random > 0.5) {
				greater += 1;
			}
			 else if (random <= 0.5) {
				lower += 1;
			}
		}
		System.out.println("> 0.5: " + greater);
		System.out.println("<= 0.5: " + lower);
		if (lower > 0 && greater > 0) {
			double ratio = (double) greater / (double) lower;
			System.out.println("Ratio: " + ratio);
			}

	}
}
